/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Dimension;
import java.awt.Toolkit;
import machine.Config;

/**
 *
 * @author admin
 */
public class FSettings extends javax.swing.JDialog {

    private Config cf;
    private boolean ResetNeeded;
    
    /**
     * Creates new form FSettings
     */
    public FSettings() {
        initComponents();
        ResetNeeded = false;
    }
    
    public boolean isResetNeeded() {
        return ResetNeeded;
    }
    
    public void showDialog(Config conf) {
        cf = conf;
        
        switch(cf.ramsize) {
            case 64:    { b64.setSelected(true); break; }
            case 256:   { b256.setSelected(true); break; }
            case 512:   { b512.setSelected(true); break; }
            case 768:   { b768.setSelected(true); break; }
            case 1024:  { b1024.setSelected(true); break; }
            default:    { b256.setSelected(true); break; }
        } //switch
        
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation((screen.width-getSize().width)/2, (screen.height-getSize().height)/2);
        setModal(true);
        setVisible(true);
    }
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RamGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRamPanel = new javax.swing.JPanel();
        b64 = new javax.swing.JRadioButton();
        b256 = new javax.swing.JRadioButton();
        b512 = new javax.swing.JRadioButton();
        b768 = new javax.swing.JRadioButton();
        b1024 = new javax.swing.JRadioButton();
        bOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Settings");
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(414, 335));
        setMinimumSize(new java.awt.Dimension(414, 335));
        setModal(true);
        setName("SettingsDlg"); // NOI18N
        setPreferredSize(new java.awt.Dimension(414, 335));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jRamPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Ram size"));

        RamGroup.add(b64);
        b64.setText("64KB");
        b64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b64ActionPerformed(evt);
            }
        });

        RamGroup.add(b256);
        b256.setText("256KB");
        b256.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b256ActionPerformed(evt);
            }
        });

        RamGroup.add(b512);
        b512.setText("512KB");
        b512.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b512ActionPerformed(evt);
            }
        });

        RamGroup.add(b768);
        b768.setText("768KB");
        b768.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b768ActionPerformed(evt);
            }
        });

        RamGroup.add(b1024);
        b1024.setText("1024KB");
        b1024.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1024ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jRamPanelLayout = new javax.swing.GroupLayout(jRamPanel);
        jRamPanel.setLayout(jRamPanelLayout);
        jRamPanelLayout.setHorizontalGroup(
            jRamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRamPanelLayout.createSequentialGroup()
                .addComponent(b64)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b256)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b512)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b768)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b1024)
                .addContainerGap())
        );
        jRamPanelLayout.setVerticalGroup(
            jRamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRamPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jRamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b256)
                    .addComponent(b512)
                    .addComponent(b768)
                    .addComponent(b1024)
                    .addComponent(b64))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        bOk.setText("Ok");
        bOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(bOk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRamPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRamPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addComponent(bOk)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void bOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOkActionPerformed
        setVisible(false);
        setModal(false);
    }//GEN-LAST:event_bOkActionPerformed

    private void b64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b64ActionPerformed
        cf.ramsize = 64;
        ResetNeeded = true;
    }//GEN-LAST:event_b64ActionPerformed
    
    private void b256ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b256ActionPerformed
        cf.ramsize = 256;
        ResetNeeded = true;
    }//GEN-LAST:event_b256ActionPerformed

    private void b512ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b512ActionPerformed
        cf.ramsize = 512;
        ResetNeeded = true;
    }//GEN-LAST:event_b512ActionPerformed

    private void b768ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b768ActionPerformed
        cf.ramsize = 768;
        ResetNeeded = true;
    }//GEN-LAST:event_b768ActionPerformed

    private void b1024ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1024ActionPerformed
        cf.ramsize = 1024;
        ResetNeeded = true;
    }//GEN-LAST:event_b1024ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup RamGroup;
    private javax.swing.JRadioButton b1024;
    private javax.swing.JRadioButton b256;
    private javax.swing.JRadioButton b512;
    private javax.swing.JRadioButton b64;
    private javax.swing.JRadioButton b768;
    private javax.swing.JButton bOk;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jRamPanel;
    // End of variables declaration//GEN-END:variables
}
